version: '3.7'

services:
  app:
    container_name: navbar-example
    build:
        context: .
        dockerfile: ../Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - '3001:3000'
    environment:
        - NODE_ENV=development